//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportesTranspesa.ServiceGRT_QA_Reversion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="en_AutenticacionGeneral", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConfirmarRespuestaReversiones))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ResumenReversion))]
    public partial class en_AutenticacionGeneral : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReportesTranspesa.ServiceGRT_QA_Reversion.en_Autenticacion ent_AutenticacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.en_Autenticacion ent_Autenticacion {
            get {
                return this.ent_AutenticacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ent_AutenticacionField, value) != true)) {
                    this.ent_AutenticacionField = value;
                    this.RaisePropertyChanged("ent_Autenticacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="en_Autenticacion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class en_Autenticacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_RucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_ClaveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_Ruc {
            get {
                return this.at_RucField;
            }
            set {
                if ((object.ReferenceEquals(this.at_RucField, value) != true)) {
                    this.at_RucField = value;
                    this.RaisePropertyChanged("at_Ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string at_Clave {
            get {
                return this.at_ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.at_ClaveField, value) != true)) {
                    this.at_ClaveField = value;
                    this.RaisePropertyChanged("at_Clave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ene_ConsultarRespuestaReversion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class ene_ConsultarRespuestaReversion : ReportesTranspesa.ServiceGRT_QA_Reversion.en_AutenticacionGeneral {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_NumeroDocumentoIdentidadField;
        
        private int at_CantidadConsultarField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_NumeroDocumentoIdentidad {
            get {
                return this.at_NumeroDocumentoIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.at_NumeroDocumentoIdentidadField, value) != true)) {
                    this.at_NumeroDocumentoIdentidadField = value;
                    this.RaisePropertyChanged("at_NumeroDocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int at_CantidadConsultar {
            get {
                return this.at_CantidadConsultarField;
            }
            set {
                if ((this.at_CantidadConsultarField.Equals(value) != true)) {
                    this.at_CantidadConsultarField = value;
                    this.RaisePropertyChanged("at_CantidadConsultar");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ene_ConfirmarRespuestaReversiones", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class ene_ConfirmarRespuestaReversiones : ReportesTranspesa.ServiceGRT_QA_Reversion.en_AutenticacionGeneral {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_NumeroDocumentoIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReportesTranspesa.ServiceGRT_QA_Reversion.ArrayOfEn_ComprobanteConfirmarReversiones l_ComprobanteConfirmarReversionesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_NumeroDocumentoIdentidad {
            get {
                return this.at_NumeroDocumentoIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.at_NumeroDocumentoIdentidadField, value) != true)) {
                    this.at_NumeroDocumentoIdentidadField = value;
                    this.RaisePropertyChanged("at_NumeroDocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ArrayOfEn_ComprobanteConfirmarReversiones l_ComprobanteConfirmarReversiones {
            get {
                return this.l_ComprobanteConfirmarReversionesField;
            }
            set {
                if ((object.ReferenceEquals(this.l_ComprobanteConfirmarReversionesField, value) != true)) {
                    this.l_ComprobanteConfirmarReversionesField = value;
                    this.RaisePropertyChanged("l_ComprobanteConfirmarReversiones");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ene_ResumenReversion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class ene_ResumenReversion : ReportesTranspesa.ServiceGRT_QA_Reversion.en_AutenticacionGeneral {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReportesTranspesa.ServiceGRT_QA_Reversion.en_Emisor ent_EmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReportesTranspesa.ServiceGRT_QA_Reversion.en_DatoResumenReversion ent_DatoResumenReversionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.en_Emisor ent_Emisor {
            get {
                return this.ent_EmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.ent_EmisorField, value) != true)) {
                    this.ent_EmisorField = value;
                    this.RaisePropertyChanged("ent_Emisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.en_DatoResumenReversion ent_DatoResumenReversion {
            get {
                return this.ent_DatoResumenReversionField;
            }
            set {
                if ((object.ReferenceEquals(this.ent_DatoResumenReversionField, value) != true)) {
                    this.ent_DatoResumenReversionField = value;
                    this.RaisePropertyChanged("ent_DatoResumenReversion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="en_Emisor", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class en_Emisor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_NumeroDocumentoIdentidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_RazonSocialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_NumeroDocumentoIdentidad {
            get {
                return this.at_NumeroDocumentoIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.at_NumeroDocumentoIdentidadField, value) != true)) {
                    this.at_NumeroDocumentoIdentidadField = value;
                    this.RaisePropertyChanged("at_NumeroDocumentoIdentidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_RazonSocial {
            get {
                return this.at_RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.at_RazonSocialField, value) != true)) {
                    this.at_RazonSocialField = value;
                    this.RaisePropertyChanged("at_RazonSocial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="en_DatoResumenReversion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class en_DatoResumenReversion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReportesTranspesa.ServiceGRT_QA_Reversion.en_CabeceraResumenReversion ent_CabeceraResumenReversionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.en_CabeceraResumenReversion ent_CabeceraResumenReversion {
            get {
                return this.ent_CabeceraResumenReversionField;
            }
            set {
                if ((object.ReferenceEquals(this.ent_CabeceraResumenReversionField, value) != true)) {
                    this.ent_CabeceraResumenReversionField = value;
                    this.RaisePropertyChanged("ent_CabeceraResumenReversion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfEn_ComprobanteConfirmarReversiones", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", ItemName="en_ComprobanteConfirmarReversiones")]
    [System.SerializableAttribute()]
    public class ArrayOfEn_ComprobanteConfirmarReversiones : System.Collections.Generic.List<ReportesTranspesa.ServiceGRT_QA_Reversion.en_ComprobanteConfirmarReversiones> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="en_ComprobanteConfirmarReversiones", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class en_ComprobanteConfirmarReversiones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_IdentificadorUnicoField;
        
        private int at_CodigoRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_IdentificadorUnico {
            get {
                return this.at_IdentificadorUnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.at_IdentificadorUnicoField, value) != true)) {
                    this.at_IdentificadorUnicoField = value;
                    this.RaisePropertyChanged("at_IdentificadorUnico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int at_CodigoRespuesta {
            get {
                return this.at_CodigoRespuestaField;
            }
            set {
                if ((this.at_CodigoRespuestaField.Equals(value) != true)) {
                    this.at_CodigoRespuestaField = value;
                    this.RaisePropertyChanged("at_CodigoRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="en_CabeceraResumenReversion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class en_CabeceraResumenReversion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_FechaComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_FechaGeneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_IdentificadorUnicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReportesTranspesa.ServiceGRT_QA_Reversion.ArrayOfEn_ComprobantesRevertidos l_ComprobantesRevertidosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_FechaComprobante {
            get {
                return this.at_FechaComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.at_FechaComprobanteField, value) != true)) {
                    this.at_FechaComprobanteField = value;
                    this.RaisePropertyChanged("at_FechaComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_FechaGeneracion {
            get {
                return this.at_FechaGeneracionField;
            }
            set {
                if ((object.ReferenceEquals(this.at_FechaGeneracionField, value) != true)) {
                    this.at_FechaGeneracionField = value;
                    this.RaisePropertyChanged("at_FechaGeneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_IdentificadorUnico {
            get {
                return this.at_IdentificadorUnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.at_IdentificadorUnicoField, value) != true)) {
                    this.at_IdentificadorUnicoField = value;
                    this.RaisePropertyChanged("at_IdentificadorUnico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ArrayOfEn_ComprobantesRevertidos l_ComprobantesRevertidos {
            get {
                return this.l_ComprobantesRevertidosField;
            }
            set {
                if ((object.ReferenceEquals(this.l_ComprobantesRevertidosField, value) != true)) {
                    this.l_ComprobantesRevertidosField = value;
                    this.RaisePropertyChanged("l_ComprobantesRevertidos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfEn_ComprobantesRevertidos", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", ItemName="en_ComprobantesRevertidos")]
    [System.SerializableAttribute()]
    public class ArrayOfEn_ComprobantesRevertidos : System.Collections.Generic.List<ReportesTranspesa.ServiceGRT_QA_Reversion.en_ComprobantesRevertidos> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="en_ComprobantesRevertidos", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class en_ComprobantesRevertidos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_TipoComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_SerieField;
        
        private int at_NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_MotivoReversionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_TipoComprobante {
            get {
                return this.at_TipoComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.at_TipoComprobanteField, value) != true)) {
                    this.at_TipoComprobanteField = value;
                    this.RaisePropertyChanged("at_TipoComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string at_Serie {
            get {
                return this.at_SerieField;
            }
            set {
                if ((object.ReferenceEquals(this.at_SerieField, value) != true)) {
                    this.at_SerieField = value;
                    this.RaisePropertyChanged("at_Serie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int at_Numero {
            get {
                return this.at_NumeroField;
            }
            set {
                if ((this.at_NumeroField.Equals(value) != true)) {
                    this.at_NumeroField = value;
                    this.RaisePropertyChanged("at_Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string at_MotivoReversion {
            get {
                return this.at_MotivoReversionField;
            }
            set {
                if ((object.ReferenceEquals(this.at_MotivoReversionField, value) != true)) {
                    this.at_MotivoReversionField = value;
                    this.RaisePropertyChanged("at_MotivoReversion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ens_Respuesta", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class ens_Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool at_NivelResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_MensajeResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_CodigoHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_NombreXMLField;
        
        private int at_CodigoErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool at_NivelResultado {
            get {
                return this.at_NivelResultadoField;
            }
            set {
                if ((this.at_NivelResultadoField.Equals(value) != true)) {
                    this.at_NivelResultadoField = value;
                    this.RaisePropertyChanged("at_NivelResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string at_MensajeResultado {
            get {
                return this.at_MensajeResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.at_MensajeResultadoField, value) != true)) {
                    this.at_MensajeResultadoField = value;
                    this.RaisePropertyChanged("at_MensajeResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string at_CodigoHash {
            get {
                return this.at_CodigoHashField;
            }
            set {
                if ((object.ReferenceEquals(this.at_CodigoHashField, value) != true)) {
                    this.at_CodigoHashField = value;
                    this.RaisePropertyChanged("at_CodigoHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string at_NombreXML {
            get {
                return this.at_NombreXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.at_NombreXMLField, value) != true)) {
                    this.at_NombreXMLField = value;
                    this.RaisePropertyChanged("at_NombreXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int at_CodigoError {
            get {
                return this.at_CodigoErrorField;
            }
            set {
                if ((this.at_CodigoErrorField.Equals(value) != true)) {
                    this.at_CodigoErrorField = value;
                    this.RaisePropertyChanged("at_CodigoError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ens_ConsultarRespuestaReversion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class ens_ConsultarRespuestaReversion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int at_NivelResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_MensajeResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReportesTranspesa.ServiceGRT_QA_Reversion.ArrayOfEn_ResultadoConsultaRespuestaReversion l_ResultadoRespuestaReversionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int at_NivelResultado {
            get {
                return this.at_NivelResultadoField;
            }
            set {
                if ((this.at_NivelResultadoField.Equals(value) != true)) {
                    this.at_NivelResultadoField = value;
                    this.RaisePropertyChanged("at_NivelResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string at_MensajeResultado {
            get {
                return this.at_MensajeResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.at_MensajeResultadoField, value) != true)) {
                    this.at_MensajeResultadoField = value;
                    this.RaisePropertyChanged("at_MensajeResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ArrayOfEn_ResultadoConsultaRespuestaReversion l_ResultadoRespuestaReversiones {
            get {
                return this.l_ResultadoRespuestaReversionesField;
            }
            set {
                if ((object.ReferenceEquals(this.l_ResultadoRespuestaReversionesField, value) != true)) {
                    this.l_ResultadoRespuestaReversionesField = value;
                    this.RaisePropertyChanged("l_ResultadoRespuestaReversiones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfEn_ResultadoConsultaRespuestaReversion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", ItemName="en_ResultadoConsultaRespuestaReversion")]
    [System.SerializableAttribute()]
    public class ArrayOfEn_ResultadoConsultaRespuestaReversion : System.Collections.Generic.List<ReportesTranspesa.ServiceGRT_QA_Reversion.en_ResultadoConsultaRespuestaReversion> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="en_ResultadoConsultaRespuestaReversion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class en_ResultadoConsultaRespuestaReversion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_NombreResumenReversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_FechaEmisionComprobantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_IdentificadorUnicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_LlaveResumenReversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReportesTranspesa.ServiceGRT_QA_Reversion.en_RespuestaReversiones ent_RespuestaReversionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string at_NombreResumenReversion {
            get {
                return this.at_NombreResumenReversionField;
            }
            set {
                if ((object.ReferenceEquals(this.at_NombreResumenReversionField, value) != true)) {
                    this.at_NombreResumenReversionField = value;
                    this.RaisePropertyChanged("at_NombreResumenReversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string at_FechaEmisionComprobantes {
            get {
                return this.at_FechaEmisionComprobantesField;
            }
            set {
                if ((object.ReferenceEquals(this.at_FechaEmisionComprobantesField, value) != true)) {
                    this.at_FechaEmisionComprobantesField = value;
                    this.RaisePropertyChanged("at_FechaEmisionComprobantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string at_IdentificadorUnico {
            get {
                return this.at_IdentificadorUnicoField;
            }
            set {
                if ((object.ReferenceEquals(this.at_IdentificadorUnicoField, value) != true)) {
                    this.at_IdentificadorUnicoField = value;
                    this.RaisePropertyChanged("at_IdentificadorUnico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string at_LlaveResumenReversion {
            get {
                return this.at_LlaveResumenReversionField;
            }
            set {
                if ((object.ReferenceEquals(this.at_LlaveResumenReversionField, value) != true)) {
                    this.at_LlaveResumenReversionField = value;
                    this.RaisePropertyChanged("at_LlaveResumenReversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.en_RespuestaReversiones ent_RespuestaReversiones {
            get {
                return this.ent_RespuestaReversionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ent_RespuestaReversionesField, value) != true)) {
                    this.ent_RespuestaReversionesField = value;
                    this.RaisePropertyChanged("ent_RespuestaReversiones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="en_RespuestaReversiones", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class en_RespuestaReversiones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int at_TipoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_FechaRespuestaField;
        
        private int at_CodigoRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_NombreXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReportesTranspesa.ServiceGRT_QA_Reversion.ArrayOfString at_MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int at_TipoRespuesta {
            get {
                return this.at_TipoRespuestaField;
            }
            set {
                if ((this.at_TipoRespuestaField.Equals(value) != true)) {
                    this.at_TipoRespuestaField = value;
                    this.RaisePropertyChanged("at_TipoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string at_Descripcion {
            get {
                return this.at_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.at_DescripcionField, value) != true)) {
                    this.at_DescripcionField = value;
                    this.RaisePropertyChanged("at_Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string at_FechaRespuesta {
            get {
                return this.at_FechaRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.at_FechaRespuestaField, value) != true)) {
                    this.at_FechaRespuestaField = value;
                    this.RaisePropertyChanged("at_FechaRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int at_CodigoRespuesta {
            get {
                return this.at_CodigoRespuestaField;
            }
            set {
                if ((this.at_CodigoRespuestaField.Equals(value) != true)) {
                    this.at_CodigoRespuestaField = value;
                    this.RaisePropertyChanged("at_CodigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string at_NombreXML {
            get {
                return this.at_NombreXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.at_NombreXMLField, value) != true)) {
                    this.at_NombreXMLField = value;
                    this.RaisePropertyChanged("at_NombreXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ArrayOfString at_Mensaje {
            get {
                return this.at_MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.at_MensajeField, value) != true)) {
                    this.at_MensajeField = value;
                    this.RaisePropertyChanged("at_Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ens_ConfirmarRespuestaReversiones", Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    [System.SerializableAttribute()]
    public partial class ens_ConfirmarRespuestaReversiones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int at_NivelResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string at_MensajeResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int at_NivelResultado {
            get {
                return this.at_NivelResultadoField;
            }
            set {
                if ((this.at_NivelResultadoField.Equals(value) != true)) {
                    this.at_NivelResultadoField = value;
                    this.RaisePropertyChanged("at_NivelResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string at_MensajeResultado {
            get {
                return this.at_MensajeResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.at_MensajeResultadoField, value) != true)) {
                    this.at_MensajeResultadoField = value;
                    this.RaisePropertyChanged("at_MensajeResultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/", ConfigurationName="ServiceGRT_QA_Reversion.IServicioReversiones")]
    public interface IServicioReversiones {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ent_ResumenReversion del espacio de nombres http://tci.net.pe/WS_eCica/Reversiones/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/RegistrarResumenRever" +
            "sion", ReplyAction="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/RegistrarResumenRever" +
            "sionResponse")]
        ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionResponse RegistrarResumenReversion(ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/RegistrarResumenRever" +
            "sion", ReplyAction="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/RegistrarResumenRever" +
            "sionResponse")]
        System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionResponse> RegistrarResumenReversionAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ent_ConsultarRespuesta del espacio de nombres http://tci.net.pe/WS_eCica/Reversiones/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionRetencion", ReplyAction="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionRetencionResponse")]
        ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionResponse ConsultarRespuestaReversionRetencion(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionRetencion", ReplyAction="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionRetencionResponse")]
        System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionResponse> ConsultarRespuestaReversionRetencionAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ent_ConsultarRespuesta del espacio de nombres http://tci.net.pe/WS_eCica/Reversiones/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionPercepcion", ReplyAction="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionPercepcionResponse")]
        ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionResponse ConsultarRespuestaReversionPercepcion(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionPercepcion", ReplyAction="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionPercepcionResponse")]
        System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionResponse> ConsultarRespuestaReversionPercepcionAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ent_ConfirmarRespuesta del espacio de nombres http://tci.net.pe/WS_eCica/Reversiones/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConfirmarRespuestaRev" +
            "ersiones", ReplyAction="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConfirmarRespuestaRev" +
            "ersionesResponse")]
        ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesResponse ConfirmarRespuestaReversiones(ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConfirmarRespuestaRev" +
            "ersiones", ReplyAction="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConfirmarRespuestaRev" +
            "ersionesResponse")]
        System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesResponse> ConfirmarRespuestaReversionesAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ent_ConsultarRespuesta del espacio de nombres http://tci.net.pe/WS_eCica/Reversiones/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionLC", ReplyAction="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionLCResponse")]
        ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCResponse ConsultarRespuestaReversionLC(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionLC", ReplyAction="http://tci.net.pe/WS_eCica/Reversiones/IServicioReversiones/ConsultarRespuestaRev" +
            "ersionLCResponse")]
        System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCResponse> ConsultarRespuestaReversionLCAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarResumenReversionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarResumenReversion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequestBody Body;
        
        public RegistrarResumenReversionRequest() {
        }
        
        public RegistrarResumenReversionRequest(ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    public partial class RegistrarResumenReversionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ResumenReversion ent_ResumenReversion;
        
        public RegistrarResumenReversionRequestBody() {
        }
        
        public RegistrarResumenReversionRequestBody(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ResumenReversion ent_ResumenReversion) {
            this.ent_ResumenReversion = ent_ResumenReversion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarResumenReversionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarResumenReversionResponse", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionResponseBody Body;
        
        public RegistrarResumenReversionResponse() {
        }
        
        public RegistrarResumenReversionResponse(ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    public partial class RegistrarResumenReversionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ens_Respuesta RegistrarResumenReversionResult;
        
        public RegistrarResumenReversionResponseBody() {
        }
        
        public RegistrarResumenReversionResponseBody(ReportesTranspesa.ServiceGRT_QA_Reversion.ens_Respuesta RegistrarResumenReversionResult) {
            this.RegistrarResumenReversionResult = RegistrarResumenReversionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRespuestaReversionRetencionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarRespuestaReversionRetencion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequestBody Body;
        
        public ConsultarRespuestaReversionRetencionRequest() {
        }
        
        public ConsultarRespuestaReversionRetencionRequest(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    public partial class ConsultarRespuestaReversionRetencionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta;
        
        public ConsultarRespuestaReversionRetencionRequestBody() {
        }
        
        public ConsultarRespuestaReversionRetencionRequestBody(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta) {
            this.ent_ConsultarRespuesta = ent_ConsultarRespuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRespuestaReversionRetencionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarRespuestaReversionRetencionResponse", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionResponseBody Body;
        
        public ConsultarRespuestaReversionRetencionResponse() {
        }
        
        public ConsultarRespuestaReversionRetencionResponse(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    public partial class ConsultarRespuestaReversionRetencionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConsultarRespuestaReversion ConsultarRespuestaReversionRetencionResult;
        
        public ConsultarRespuestaReversionRetencionResponseBody() {
        }
        
        public ConsultarRespuestaReversionRetencionResponseBody(ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConsultarRespuestaReversion ConsultarRespuestaReversionRetencionResult) {
            this.ConsultarRespuestaReversionRetencionResult = ConsultarRespuestaReversionRetencionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRespuestaReversionPercepcionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarRespuestaReversionPercepcion", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequestBody Body;
        
        public ConsultarRespuestaReversionPercepcionRequest() {
        }
        
        public ConsultarRespuestaReversionPercepcionRequest(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    public partial class ConsultarRespuestaReversionPercepcionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta;
        
        public ConsultarRespuestaReversionPercepcionRequestBody() {
        }
        
        public ConsultarRespuestaReversionPercepcionRequestBody(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta) {
            this.ent_ConsultarRespuesta = ent_ConsultarRespuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRespuestaReversionPercepcionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarRespuestaReversionPercepcionResponse", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionResponseBody Body;
        
        public ConsultarRespuestaReversionPercepcionResponse() {
        }
        
        public ConsultarRespuestaReversionPercepcionResponse(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    public partial class ConsultarRespuestaReversionPercepcionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConsultarRespuestaReversion ConsultarRespuestaReversionPercepcionResult;
        
        public ConsultarRespuestaReversionPercepcionResponseBody() {
        }
        
        public ConsultarRespuestaReversionPercepcionResponseBody(ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConsultarRespuestaReversion ConsultarRespuestaReversionPercepcionResult) {
            this.ConsultarRespuestaReversionPercepcionResult = ConsultarRespuestaReversionPercepcionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmarRespuestaReversionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmarRespuestaReversiones", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequestBody Body;
        
        public ConfirmarRespuestaReversionesRequest() {
        }
        
        public ConfirmarRespuestaReversionesRequest(ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    public partial class ConfirmarRespuestaReversionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConfirmarRespuestaReversiones ent_ConfirmarRespuesta;
        
        public ConfirmarRespuestaReversionesRequestBody() {
        }
        
        public ConfirmarRespuestaReversionesRequestBody(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConfirmarRespuestaReversiones ent_ConfirmarRespuesta) {
            this.ent_ConfirmarRespuesta = ent_ConfirmarRespuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmarRespuestaReversionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmarRespuestaReversionesResponse", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesResponseBody Body;
        
        public ConfirmarRespuestaReversionesResponse() {
        }
        
        public ConfirmarRespuestaReversionesResponse(ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    public partial class ConfirmarRespuestaReversionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConfirmarRespuestaReversiones ConfirmarRespuestaReversionesResult;
        
        public ConfirmarRespuestaReversionesResponseBody() {
        }
        
        public ConfirmarRespuestaReversionesResponseBody(ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConfirmarRespuestaReversiones ConfirmarRespuestaReversionesResult) {
            this.ConfirmarRespuestaReversionesResult = ConfirmarRespuestaReversionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRespuestaReversionLCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarRespuestaReversionLC", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequestBody Body;
        
        public ConsultarRespuestaReversionLCRequest() {
        }
        
        public ConsultarRespuestaReversionLCRequest(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    public partial class ConsultarRespuestaReversionLCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta;
        
        public ConsultarRespuestaReversionLCRequestBody() {
        }
        
        public ConsultarRespuestaReversionLCRequestBody(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta) {
            this.ent_ConsultarRespuesta = ent_ConsultarRespuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRespuestaReversionLCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarRespuestaReversionLCResponse", Namespace="http://tci.net.pe/WS_eCica/Reversiones/", Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCResponseBody Body;
        
        public ConsultarRespuestaReversionLCResponse() {
        }
        
        public ConsultarRespuestaReversionLCResponse(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tci.net.pe/WS_eCica/Reversiones/")]
    public partial class ConsultarRespuestaReversionLCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConsultarRespuestaReversion ConsultarRespuestaReversionLCResult;
        
        public ConsultarRespuestaReversionLCResponseBody() {
        }
        
        public ConsultarRespuestaReversionLCResponseBody(ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConsultarRespuestaReversion ConsultarRespuestaReversionLCResult) {
            this.ConsultarRespuestaReversionLCResult = ConsultarRespuestaReversionLCResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioReversionesChannel : ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioReversionesClient : System.ServiceModel.ClientBase<ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones>, ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones {
        
        public ServicioReversionesClient() {
        }
        
        public ServicioReversionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioReversionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReversionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReversionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionResponse ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones.RegistrarResumenReversion(ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequest request) {
            return base.Channel.RegistrarResumenReversion(request);
        }
        
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ens_Respuesta RegistrarResumenReversion(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ResumenReversion ent_ResumenReversion) {
            ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequest inValue = new ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequest();
            inValue.Body = new ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequestBody();
            inValue.Body.ent_ResumenReversion = ent_ResumenReversion;
            ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionResponse retVal = ((ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones)(this)).RegistrarResumenReversion(inValue);
            return retVal.Body.RegistrarResumenReversionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionResponse> ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones.RegistrarResumenReversionAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequest request) {
            return base.Channel.RegistrarResumenReversionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionResponse> RegistrarResumenReversionAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ResumenReversion ent_ResumenReversion) {
            ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequest inValue = new ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequest();
            inValue.Body = new ReportesTranspesa.ServiceGRT_QA_Reversion.RegistrarResumenReversionRequestBody();
            inValue.Body.ent_ResumenReversion = ent_ResumenReversion;
            return ((ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones)(this)).RegistrarResumenReversionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionResponse ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones.ConsultarRespuestaReversionRetencion(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequest request) {
            return base.Channel.ConsultarRespuestaReversionRetencion(request);
        }
        
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConsultarRespuestaReversion ConsultarRespuestaReversionRetencion(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta) {
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequest inValue = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequest();
            inValue.Body = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequestBody();
            inValue.Body.ent_ConsultarRespuesta = ent_ConsultarRespuesta;
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionResponse retVal = ((ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones)(this)).ConsultarRespuestaReversionRetencion(inValue);
            return retVal.Body.ConsultarRespuestaReversionRetencionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionResponse> ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones.ConsultarRespuestaReversionRetencionAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequest request) {
            return base.Channel.ConsultarRespuestaReversionRetencionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionResponse> ConsultarRespuestaReversionRetencionAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta) {
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequest inValue = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequest();
            inValue.Body = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionRetencionRequestBody();
            inValue.Body.ent_ConsultarRespuesta = ent_ConsultarRespuesta;
            return ((ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones)(this)).ConsultarRespuestaReversionRetencionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionResponse ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones.ConsultarRespuestaReversionPercepcion(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequest request) {
            return base.Channel.ConsultarRespuestaReversionPercepcion(request);
        }
        
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConsultarRespuestaReversion ConsultarRespuestaReversionPercepcion(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta) {
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequest inValue = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequest();
            inValue.Body = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequestBody();
            inValue.Body.ent_ConsultarRespuesta = ent_ConsultarRespuesta;
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionResponse retVal = ((ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones)(this)).ConsultarRespuestaReversionPercepcion(inValue);
            return retVal.Body.ConsultarRespuestaReversionPercepcionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionResponse> ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones.ConsultarRespuestaReversionPercepcionAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequest request) {
            return base.Channel.ConsultarRespuestaReversionPercepcionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionResponse> ConsultarRespuestaReversionPercepcionAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta) {
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequest inValue = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequest();
            inValue.Body = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionPercepcionRequestBody();
            inValue.Body.ent_ConsultarRespuesta = ent_ConsultarRespuesta;
            return ((ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones)(this)).ConsultarRespuestaReversionPercepcionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesResponse ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones.ConfirmarRespuestaReversiones(ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequest request) {
            return base.Channel.ConfirmarRespuestaReversiones(request);
        }
        
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConfirmarRespuestaReversiones ConfirmarRespuestaReversiones(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConfirmarRespuestaReversiones ent_ConfirmarRespuesta) {
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequest inValue = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequest();
            inValue.Body = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequestBody();
            inValue.Body.ent_ConfirmarRespuesta = ent_ConfirmarRespuesta;
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesResponse retVal = ((ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones)(this)).ConfirmarRespuestaReversiones(inValue);
            return retVal.Body.ConfirmarRespuestaReversionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesResponse> ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones.ConfirmarRespuestaReversionesAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequest request) {
            return base.Channel.ConfirmarRespuestaReversionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesResponse> ConfirmarRespuestaReversionesAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConfirmarRespuestaReversiones ent_ConfirmarRespuesta) {
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequest inValue = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequest();
            inValue.Body = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConfirmarRespuestaReversionesRequestBody();
            inValue.Body.ent_ConfirmarRespuesta = ent_ConfirmarRespuesta;
            return ((ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones)(this)).ConfirmarRespuestaReversionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCResponse ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones.ConsultarRespuestaReversionLC(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequest request) {
            return base.Channel.ConsultarRespuestaReversionLC(request);
        }
        
        public ReportesTranspesa.ServiceGRT_QA_Reversion.ens_ConsultarRespuestaReversion ConsultarRespuestaReversionLC(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta) {
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequest inValue = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequest();
            inValue.Body = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequestBody();
            inValue.Body.ent_ConsultarRespuesta = ent_ConsultarRespuesta;
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCResponse retVal = ((ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones)(this)).ConsultarRespuestaReversionLC(inValue);
            return retVal.Body.ConsultarRespuestaReversionLCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCResponse> ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones.ConsultarRespuestaReversionLCAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequest request) {
            return base.Channel.ConsultarRespuestaReversionLCAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCResponse> ConsultarRespuestaReversionLCAsync(ReportesTranspesa.ServiceGRT_QA_Reversion.ene_ConsultarRespuestaReversion ent_ConsultarRespuesta) {
            ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequest inValue = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequest();
            inValue.Body = new ReportesTranspesa.ServiceGRT_QA_Reversion.ConsultarRespuestaReversionLCRequestBody();
            inValue.Body.ent_ConsultarRespuesta = ent_ConsultarRespuesta;
            return ((ReportesTranspesa.ServiceGRT_QA_Reversion.IServicioReversiones)(this)).ConsultarRespuestaReversionLCAsync(inValue);
        }
    }
}
